version: "3.8"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.38:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper

# Commented out since you want to run it outside Docker
#  user-service:
#    build: .
#    ports:
#      - "5000:5000"
#    environment:
#      - MONGO_URI=mongodb+srv://outdid:outdid@cluster0.t16a63a.mongodb.net/userdb?retryWrites=true&w=majority
#      - KAFKA_BROKER=192.168.1.38:9092
#      - DUMMY_USER_ID=123e4567-e89b-12d3-a456-426614174000
#      - PORT=5000
#    depends_on:
#      - kafka
